// Mock data for testing without TMDB API key
export const mockTrending = {
    results: [
        {
            id: 1,
            title: "الفيلم الأول",
            name: "The First Movie",
            overview: "فيلم مثير ومشوق يحكي قصة بطل يحاول إنقاذ العالم من الدمار. مليء بالأكشن والمغامرات.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 8.5,
            release_date: "2024-01-15",
            first_air_date: "2024-01-15",
            media_type: "movie",
        },
        {
            id: 2,
            title: "المغامرة الكبرى",
            name: "The Great Adventure",
            overview: "رحلة مذهلة عبر الزمن والمكان في عالم خيالي مليء بالمخاطر والاكتشافات.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 7.8,
            release_date: "2024-02-20",
            first_air_date: "2024-02-20",
            media_type: "movie",
        },
        {
            id: 3,
            title: "ليلة الرعب",
            name: "Night of Terror",
            overview: "قصة مرعبة في منزل قديم حيث تحدث أحداث غريبة وغامضة.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 7.2,
            release_date: "2023-10-31",
            first_air_date: "2023-10-31",
            media_type: "movie",
        },
        {
            id: 4,
            title: "الحب في باريس",
            name: "Love in Paris",
            overview: "قصة حب رومانسية تجمع بين شخصين من عالمين مختلفين في مدينة الأنوار.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 8.1,
            release_date: "2024-02-14",
            first_air_date: "2024-02-14",
            media_type: "movie",
        },
        {
            id: 5,
            title: "المحقق الذكي",
            name: "The Smart Detective",
            overview: "مسلسل بوليسي مثير يتتبع محققاً عبقرياً في حل أصعب القضايا الغامضة.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 9.0,
            release_date: "2024-03-01",
            first_air_date: "2024-03-01",
            media_type: "tv",
        },
        {
            id: 6,
            title: "عالم الخيال",
            name: "Fantasy World",
            overview: "مسلسل خيالي ملحمي في عالم مليء بالسحر والمخلوقات الأسطورية.",
            poster_path: null,
            backdrop_path: null,
            vote_average: 8.7,
            release_date: "2024-01-10",
            first_air_date: "2024-01-10",
            media_type: "tv",
        },
    ],
};

export const mockMovies = {
    results: [
        { id: 101, title: "صراع البقاء", overview: "فيلم أكشن مثير", poster_path: null, backdrop_path: null, vote_average: 7.5, release_date: "2024-01-05" },
        { id: 102, title: "الهروب الكبير", overview: "مغامرة شيقة", poster_path: null, backdrop_path: null, vote_average: 8.0, release_date: "2024-02-10" },
        { id: 103, title: "قلب الظلام", overview: "دراما نفسية عميقة", poster_path: null, backdrop_path: null, vote_average: 8.3, release_date: "2024-03-15" },
        { id: 104, title: "الفرسان الثلاثة", overview: "فيلم تاريخي ملحمي", poster_path: null, backdrop_path: null, vote_average: 7.8, release_date: "2024-01-20" },
        { id: 105, title: "رحلة النجوم", overview: "خيال علمي مذهل", poster_path: null, backdrop_path: null, vote_average: 8.9, release_date: "2024-02-25" },
        { id: 106, title: "الوحش", overview: "فيلم رعب مخيف", poster_path: null, backdrop_path: null, vote_average: 6.5, release_date: "2023-10-15" },
        { id: 107, title: "حكاية حب", overview: "رومانسية جميلة", poster_path: null, backdrop_path: null, vote_average: 7.9, release_date: "2024-02-14" },
        { id: 108, title: "الملك الأخير", overview: "دراما تاريخية", poster_path: null, backdrop_path: null, vote_average: 8.2, release_date: "2024-03-01" },
        { id: 109, title: "سرعة الضوء", overview: "سباق مثير", poster_path: null, backdrop_path: null, vote_average: 7.0, release_date: "2024-01-30" },
        { id: 110, title: "العودة", overview: "فيلم دراما", poster_path: null, backdrop_path: null, vote_average: 8.5, release_date: "2024-02-05" },
        { id: 111, title: "المحارب", overview: "أكشن ملحمي", poster_path: null, backdrop_path: null, vote_average: 7.7, release_date: "2024-03-10" },
        { id: 112, title: "الغريب", overview: "غموض وإثارة", poster_path: null, backdrop_path: null, vote_average: 8.1, release_date: "2024-01-25" },
    ],
    total_pages: 10,
    page: 1,
};

export const mockTVShows = {
    results: [
        { id: 201, name: "عائلة السعادة", overview: "مسلسل عائلي كوميدي", poster_path: null, backdrop_path: null, vote_average: 8.0, first_air_date: "2024-01-01", media_type: "tv" },
        { id: 202, name: "المستشفى", overview: "دراما طبية", poster_path: null, backdrop_path: null, vote_average: 8.5, first_air_date: "2024-02-01", media_type: "tv" },
        { id: 203, name: "جريمة في الليل", overview: "مسلسل بوليسي", poster_path: null, backdrop_path: null, vote_average: 9.0, first_air_date: "2024-01-15", media_type: "tv" },
        { id: 204, name: "أسرار القلوب", overview: "دراما رومانسية", poster_path: null, backdrop_path: null, vote_average: 7.5, first_air_date: "2024-03-01", media_type: "tv" },
        { id: 205, name: "المملكة", overview: "تاريخي ملحمي", poster_path: null, backdrop_path: null, vote_average: 8.8, first_air_date: "2024-02-10", media_type: "tv" },
        { id: 206, name: "الكوكب الأزرق", overview: "وثائقي علمي", poster_path: null, backdrop_path: null, vote_average: 9.2, first_air_date: "2024-01-20", media_type: "tv" },
        { id: 207, name: "مدرسة الأبطال", overview: "أنمي أكشن", poster_path: null, backdrop_path: null, vote_average: 8.6, first_air_date: "2024-02-15", media_type: "tv" },
        { id: 208, name: "البيت الكبير", overview: "دراما عائلية", poster_path: null, backdrop_path: null, vote_average: 7.8, first_air_date: "2024-03-05", media_type: "tv" },
        { id: 209, name: "محامي العدالة", overview: "دراما قانونية", poster_path: null, backdrop_path: null, vote_average: 8.3, first_air_date: "2024-01-25", media_type: "tv" },
        { id: 210, name: "رحلات الفضاء", overview: "خيال علمي", poster_path: null, backdrop_path: null, vote_average: 8.7, first_air_date: "2024-02-20", media_type: "tv" },
    ],
    total_pages: 8,
    page: 1,
};

export const mockGenres = [
    { id: 28, name: "أكشن" },
    { id: 12, name: "مغامرة" },
    { id: 16, name: "رسوم متحركة" },
    { id: 35, name: "كوميديا" },
    { id: 80, name: "جريمة" },
    { id: 99, name: "وثائقي" },
    { id: 18, name: "دراما" },
    { id: 10751, name: "عائلي" },
    { id: 14, name: "خيال" },
    { id: 36, name: "تاريخ" },
    { id: 27, name: "رعب" },
    { id: 10402, name: "موسيقى" },
    { id: 9648, name: "غموض" },
    { id: 10749, name: "رومانسي" },
    { id: 878, name: "خيال علمي" },
    { id: 53, name: "إثارة" },
    { id: 10752, name: "حرب" },
    { id: 37, name: "غربي" },
];

export const mockDetails = {
    id: 1,
    title: "الفيلم الأول",
    name: "The First Movie",
    tagline: "المغامرة تبدأ هنا",
    overview: "فيلم مثير ومشوق يحكي قصة بطل يحاول إنقاذ العالم من الدمار. مليء بالأكشن والمغامرات والمفاجآت التي ستبقيك على حافة مقعدك. قصة عن الشجاعة والتضحية والأمل في مواجهة أعظم التحديات.",
    poster_path: null,
    backdrop_path: null,
    vote_average: 8.5,
    release_date: "2024-01-15",
    first_air_date: "2024-01-15",
    runtime: 142,
    number_of_seasons: 3,
    number_of_episodes: 24,
    genres: [
        { id: 28, name: "أكشن" },
        { id: 12, name: "مغامرة" },
        { id: 878, name: "خيال علمي" },
    ],
    seasons: [
        { id: 1, season_number: 1, name: "Season 1", episode_count: 8 },
        { id: 2, season_number: 2, name: "Season 2", episode_count: 8 },
        { id: 3, season_number: 3, name: "Season 3", episode_count: 8 },
    ],
    credits: {
        cast: [
            { id: 1, name: "أحمد السعيد", character: "البطل", profile_path: null },
            { id: 2, name: "سارة الأحمد", character: "المساعدة", profile_path: null },
            { id: 3, name: "محمد العلي", character: "الشرير", profile_path: null },
            { id: 4, name: "نور الدين", character: "الحكيم", profile_path: null },
            { id: 5, name: "ليلى حسن", character: "الأميرة", profile_path: null },
        ],
    },
    videos: {
        results: [
            { key: "dQw4w9WgXcQ", type: "Trailer", site: "YouTube" },
        ],
    },
    similar: {
        results: mockMovies.results.slice(0, 6),
    },
    recommendations: {
        results: mockMovies.results.slice(0, 6),
    },
};
